//Clasificación-tipo-subtipo
export const RULES = {
  //CASOS
  '04-12-64': { //Reclamos - Atención al Cliente - Insatisfacción de respuesta
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '03',
  },
  '04-12-32': { //Reclamos - Atención al Cliente - Agresión
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '08',
  },
  '04-12-33': { //Reclamos - Atención al Cliente - Accidentes
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
  '04-12-34': { //Reclamos - Atención al Cliente - Atención del personal
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '08',
  },
  '04-12-35': { //Reclamos - Atención al Cliente - Ingreso mascotas
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
  '04-12-65': { //Reclamos - Atención al Cliente - Ingreso bultos / carros
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
  '04-12-66': { //Reclamos - Atención al Cliente - Ingreso bicicletas
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
  '04-12-67': { //Reclamos - Atención al Cliente - Acceso baños
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
  '04-12-68': { //Reclamos - Atención al Cliente - Ingreso liberado
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
  '04-12-36': { //Reclamos - Atención al Cliente - Fonos de emergencia 1411-1488
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['nCarroTren','linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '01',
  },
  '04-12-37': { //Reclamos - Atención al Cliente - Fono asistencia 800
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '01',
  },
  '04-13-18': { //Reclamos - Estaciones - Boleterias
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '02',
  },
  '04-13-19': { //Reclamos - Estaciones - Máquinas de autoservicio
    hidden: ['direccion','comuna','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','medioDePago','nDeTarjeta','monto','nMaquinaVendedor'],
    optional: ['nCarroTren'],
    equipoGestionador: '02',
  },
  '04-13-69': { //Reclamos - Estaciones - Máquinas de autoservicio L3 L6
    hidden: ['direccion','comuna','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','medioDePago','nDeTarjeta','monto','nMaquinaVendedor'],
    optional: ['nCarroTren'],
    equipoGestionador: '02',
  },
  '04-13-70': { //Reclamos - Estaciones - Máquinas de autoservicio L1 L2 L4 L4A L5
    hidden: ['direccion','comuna','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','medioDePago','nDeTarjeta','monto','nMaquinaVendedor'],
    optional: ['nCarroTren'],
    equipoGestionador: '02',
  },
  '04-13-71': { //Reclamos - Estaciones - Máquinas de autoservicio no operativa
    hidden: ['direccion','comuna','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','medioDePago','nDeTarjeta','monto','nMaquinaVendedor'],
    optional: ['nCarroTren'],
    equipoGestionador: '02',
  },
  '04-13-20': { //Reclamos - Estaciones - Objetos no recuperados
    hidden: ['direccion','comuna','nDeTarjeta','monto','datosTicket','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '09',
  },
   '04-14-38': { //Reclamos - Trenes / viaje - Conducción
    hidden: ['direccion','comuna','nDeTarjeta','monto','datosTicket','nMaquinaVendedor'],
    required: ['linea','nCarroTren','fechaIncidente','horaIncidente'],
    optional: ['estacion','medioDePago'],
    equipoGestionador: '09',
  },
  '04-15-72': { //Reclamos - Medios de pago - Activación ticket de viaje
    hidden: ['nCarroTren','direccion','comuna','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','medioDePago','nDeTarjeta','datosTicket'],
    optional: ['horaIncidente'],
    equipoGestionador: '02',
  },
  '04-15-22': { //Reclamos - Medios de pago - Ticket de viaje
    hidden: ['nCarroTren','direccion','comuna','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','medioDePago','nDeTarjeta','datosTicket'],
    optional: ['horaIncidente'],
    equipoGestionador: '02',
  },
   '04-15-23': { //Reclamos - Medios de pago - MetroMuv
    hidden: ['nCarroTren','direccion','comuna','monto','nMaquinaVendedor','datosTicket'],
    required: ['estacion','fechaIncidente','medioDePago','nDeTarjeta'],
    optional: ['linea','horaIncidente'],
    equipoGestionador: '04',
  },
   '04-15-24': { //Reclamos - Medios de pago - Saldo caducado
    hidden: ['nCarroTren','direccion','comuna','monto','nMaquinaVendedor','datosTicket'],
    required: ['estacion','medioDePago','nDeTarjeta'],
    optional: ['linea','fechaIncidente','horaIncidente'],
    equipoGestionador: '02',
  },
  '04-16-43': { //Reclamos - Entorno / Perímetro - Aseo
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-16-44': { //Reclamos - Entorno / Perímetro - Luminaria
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-16-45': { //Reclamos - Entorno / Perímetro - Persona situación calle
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-16-46': { //Reclamos - Entorno / Perímetro - Ruidos molestos
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-16-47': { //Reclamos - Entorno / Perímetro - Seguridad / comercio ilegal
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-17-48': { //Reclamos - Viaducto - Aseo
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-17-49': { //Reclamos - Viaducto - Luminaria
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-17-50': { //Reclamos - Viaducto - Persona situación calle
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-18-51': { //Reclamos - Terrenos Metro - Seguridad
    hidden: ['nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','direccion','comuna'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-18-52': { //Reclamos - Terrenos Metro - Persona situación calle
    hidden: ['nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','direccion','comuna'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-18-53': { //Reclamos - Terrenos Metro - Mantenimiento general (desmalezado)
    hidden: ['nCarroTren','horaIncidente','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','fechaIncidente','direccion','comuna'],
    optional: ['estacion','medioDePago'],
    equipoGestionador: '06',
  },
  '04-19-54': { //Reclamos - Talleres / cocheras - Ruidos molestos
    hidden: ['nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','direccion','comuna'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-19-55': { //Reclamos - Talleres / cocheras - Mantenimiento general
    hidden: ['nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','direccion','comuna'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-20': { //Reclamos - Vibraciones / daño estructural
    hidden: ['nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket','subtipo'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','direccion','comuna'],
    optional: ['medioDePago'],
    equipoGestionador: '06',
  },
  '04-21-27': { //Reclamos - Nuevas Líneas - Tramo
    hidden: ['estacion','nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','direccion','comuna'],
    optional: ['medioDePago','fechaIncidente','horaIncidente'],
    equipoGestionador: '06',
  },
  '04-21-28': { //Reclamos - Nuevas Líneas - Nombre
    hidden: ['estacion','nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','direccion','comuna'],
    optional: ['medioDePago','fechaIncidente','horaIncidente'],
    equipoGestionador: '06',
  },
  '04-21-29': { //Reclamos - Nuevas Líneas - Expropiación
    hidden: ['estacion','nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','direccion','comuna'],
    optional: ['medioDePago','fechaIncidente','horaIncidente'],
    equipoGestionador: '06',
  },
  '04-21-30': { //Reclamos - Nuevas Líneas - Obras en construcción
    hidden: ['estacion','nCarroTren','monto','nDeTarjeta','nMaquinaVendedor','datosTicket'],
    required: ['linea','direccion','comuna'],
    optional: ['medioDePago','fechaIncidente','horaIncidente'],
    equipoGestionador: '06',
  },
  '01-01': { //Consultas - Objeto Extraviado
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','nMaquinaVendedor','datosTicket','subtipo'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '03',
  },
  '01-02-01': { //Consultas - Oficina de atención al cliente - Proceso TAM / TBAM
    hidden: ['nCarroTren','direccion','comuna','monto','nMaquinaVendedor','datosTicket'],
    required: [],
    optional: ['linea','estacion','medioDePago','fechaIncidente','horaIncidente','nDeTarjeta'],
    equipoGestionador: '05',
  },
  '01-03': { //Consultas - Ticket de viaje
    hidden: ['nCarroTren','direccion','comuna','monto','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion','fechaIncidente','horaIncidente','medioDePago','nDeTarjeta','datosTicket'],
    optional: [],
    equipoGestionador: '02',
  },
  '01-04': { //Consultas - Nuevas líneas
    hidden: ['nCarroTren','monto','nDeTarjeta','datosTicket','nMaquinaVendedor','subtipo'],
    required: ['linea','direccion','comuna'],
    optional: ['estacion','fechaIncidente','horaIncidente','medioDePago'],
    equipoGestionador: '07',
  },
  '03-09': { //Gestión interna - Ley de transparencia
    hidden: ['nCarroTren','horaIncidente','direccion','comuna','monto','nDeTarjeta','datosTicket','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion'],
    optional: ['fechaIncidente','medioDePago'],
    equipoGestionador: '03',
  },
  '03-10': { //Gestión interna - Oficios
    hidden: ['nCarroTren','horaIncidente','direccion','comuna','monto','nDeTarjeta','datosTicket','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion'],
    optional: ['fechaIncidente','medioDePago'],
    equipoGestionador: '03',
  },
  '03-11': { //Gestión interna - Otros
    hidden: ['nCarroTren','direccion','comuna','monto','nDeTarjeta','datosTicket','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion'],
    optional: ['fechaIncidente','horaIncidente','medioDePago'],
    equipoGestionador: '03',
  },

  //EVENTOS

  '04-22-56': { //Reclamos - General - Equipos mal funcionamiento / fuera de servicio
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '',
  },
  '04-22-57': { //Reclamos - General - Seguridad
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '',
  },
  '04-22-58': { //Reclamos - General - Aseo
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['nCarroTren','medioDePago'],
    equipoGestionador: '',
  },
  '04-22-59': { //Reclamos - General - Servicios de combinación
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '04-22-60': { //Reclamos - General - Entrega ticket de viaje
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '04-22-61': { //Reclamos - General - 61 Otros (Horario de servicio, Información pasajero)
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },

  '04-23-31': { //Reclamos - Oficina de atención al cliente - Atención de ejecutivos/as
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '04-24-62': { //Reclamos - Deficiencia en la información - Trenes, estaciones, etc
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','nCarroTren','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '04-14-39': { //Reclamos - Trenes / viaje - Retraso frecuencia, Servicio parcial, Ruta expresa, Mal funcionamiento / fuera de servicio
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','estacion'],
    equipoGestionador: '',
  },
  '04-14-40': { //Reclamos - Trenes / viaje - Justificativo
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','estacion'],
    equipoGestionador: '',
  },
  '04-14-41': { //Reclamos - Trenes / viaje - Seguridad
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','nCarroTren','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','estacion'],
    equipoGestionador: '',
  },
   '04-14-42': { //Reclamos - Trenes / viaje - Aseo
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','nCarroTren','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','estacion'],
    equipoGestionador: '',
  },
  '04-14-63': { //Reclamos - Trenes / viaje - Instalaciones defectuosas
    hidden: ['direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','nCarroTren','fechaIncidente'],
    optional: ['medioDePago','estacion','horaIncidente'],
    equipoGestionador: '',
  },
  '04-15-25': { //Reclamos - Medios de pago - Problemas de uso y falla
    hidden: ['nCarroTren','direccion','comuna','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','nDeTarjeta'],
    equipoGestionador: '',
  },
  '04-15-26': { //Reclamos - Medios de pago - Cobro indebido
    hidden: ['nCarroTren','direccion','comuna','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','nDeTarjeta'],
    equipoGestionador: '',
  },
  '04-15-21': { //Reclamos - Medios de pago - Traspaso de saldo
    hidden: ['nCarroTren','direccion','comuna','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago','nDeTarjeta'],
    equipoGestionador: '',
  },
  '01-05-02': { //Consultas - Estaciones - Horarios de servicio
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-05-03': { //Consultas - Estaciones - Objeto caído a las vías
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-05-04': { //Consultas - Estaciones - Información al pasajero
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-05-05': { //Consultas - Estaciones - Acceso liberado
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-06-06': { //Consultas - Solicitudes - visitas guiadas
    hidden: ['linea','estacion','fechaIncidente','horaIncidente','nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: [],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-06-07': { //Consultas - Solicitudes - Mercado a un metro
    hidden: ['linea','estacion','fechaIncidente','horaIncidente','nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: [],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-06-08': { //Consultas - Solicitudes - Justificativo
    hidden: ['estacion','nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-06-09': { //Consultas - Solicitudes - Empleo / práctica
    hidden: ['linea','estacion','fechaIncidente','horaIncidente','nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: [],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-06-10': { //Consultas - Solicitudes - Tarifas diferenciadas
    hidden: ['linea','estacion','fechaIncidente','horaIncidente','nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: [],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '01-06-11': { //Consultas - Solicitudes - Otras
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion'],
    optional: ['medioDePago','fechaIncidente','horaIncidente'],
    equipoGestionador: '',
  },
  '05-25': { //Sugerencias - Medios de pago
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion'],
    optional: ['medioDePago','fechaIncidente','horaIncidente'],
    equipoGestionador: '',
  },
  '05-26': { //Sugerencias - Instalaciones
    hidden: ['nCarroTren','fechaIncidente','horaIncidente','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '05-27': { //Sugerencias - Señalética
    hidden: ['direccion','comuna','horaIncidente','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion','nCarroTren'],
    optional: ['medioDePago','fechaIncidente'],
    equipoGestionador: '',
  },
  '05-28': { //Sugerencias - Campañas informativas
    hidden: ['direccion','comuna','horaIncidente','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: ['linea','estacion','nCarroTren'],
    optional: ['medioDePago','fechaIncidente'],
    equipoGestionador: '',
  },
  '05-29': { //Sugerencias - Nuevas líneas
    hidden: ['estacion','nCarroTren','fechaIncidente','direccion','comuna','horaIncidente','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: ['linea'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '05-30': { //Sugerencias - Otros (Validar Dinamo)
    hidden: ['linea','estacion','horaIncidente','nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: [],
    optional: ['fechaIncidente','medioDePago'],
    equipoGestionador: '',
  },
  '02-07-12': { //Felicitaciones - Atención personal - Vigilantes
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
  '02-07-13': { //Felicitaciones - Atención personal - Guardias
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
   '02-07-14': { //Felicitaciones - Atención personal - Asistente
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
   '02-07-15': { //Felicitaciones - Atención personal - Jefe de estación
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
   '02-07-16': { //Felicitaciones - Atención personal - Cajero
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
   '02-07-17': { //Felicitaciones - Atención personal - Personal en general
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor'],
    required: ['linea','estacion','fechaIncidente','horaIncidente'],
    optional: ['medioDePago'],
    equipoGestionador: '',
  },
   '02-08': { //Felicitaciones - Servicio
    hidden: ['nCarroTren','direccion','comuna','nDeTarjeta','datosTicket','monto','nMaquinaVendedor','subtipo'],
    required: [],
    optional: ['linea','estacion','fechaIncidente','horaIncidente','medioDePago'],
    equipoGestionador: '',
  },
};
